server:
  port: 9090

spring:
  application:
    name: ai_db_mcp
  ai:
    mcp:
      server:
        protocol: STATELESS
        annotation-scanner:
          enabled: true
          base-packages:
            - com.aidb.mcp
        capabilities:
          tool: true

logging:
  level:
    com.aidb.mcp: DEBUG
    org.springframework.ai: DEBUG
